name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test -test.shuffle on -test.run . -test.v -vet '' ./...
      # fuzz the generic command parser
      - run: go test -test.shuffle on -test.fuzz FuzzServerParser -test.fuzztime 5m
      # fuzz readArgs and check that it produces the same as the original redis sdssplitargs function
      - run: go test -test.shuffle on -test.fuzz FuzzSplitArgs -test.fuzztime 5m
