name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test -test.shuffle on -test.fuzz . -test.fuzztime 5m -test.run . -test.v -vet ''
